# Generated by Django 5.1.1 on 2025-02-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GemstoneImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gemstones/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColorAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rgb", models.CharField(max_length=20)),
                ("css_color_code", models.CharField(max_length=7)),
                ("brightness", models.FloatField()),
                ("color_ratios", models.CharField(max_length=50)),
                ("density", models.FloatField()),
                ("closest_colors", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gemstone_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gemstone_app.gemstoneimage",
                    ),
                ),
            ],
        ),
    ]
